# Generated by Django 2.2.1 on 2019-06-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
        ('music', '0003_auto_20190608_1621'),
    ]

    operations = [
    ]
